/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.CategoriaDAO;
import DAO.ProdutoDAO;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Categoria;
import model.Produto;

/**
 *
 * @author Klayton Massango
 */
public final class ViewProdutos extends javax.swing.JFrame {

    /**
     * Creates new form ViewProdutos
     *
     */
    public void listar() {
        ProdutoDAO dao = new ProdutoDAO();
        List<Produto> lista = dao.listarProdutos();
        DefaultTableModel dados = (DefaultTableModel) jPro_tabela.getModel();
        dados.setNumRows(0);

        for (Produto p : lista) {
            dados.addRow(new Object[]{
                p.getId_produto(),
                p.getPro_nome(),
                p.getPro_categoria(),
                p.getPro_quantidade(),
                p.getPro_preco(),});
        }
    }

    public void listarCategorias() {
        CategoriaDAO dao = new CategoriaDAO();
        List<Categoria> lista = dao.listarCategorias();

        jPro_categoria.removeAllItems();
        for (Categoria cat : lista) {
            jPro_categoria.addItem(cat.toString());
        }
    }

    public ViewProdutos() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setIconImage();
    }

    public void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPro_tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPro_codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPro_quantidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPro_preco = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPro_nome = new javax.swing.JTextField();
        jPro_categoria = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPro_pesquisar = new javax.swing.JTextField();
        jBPro_pesquisar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jBtn_excluir = new javax.swing.JButton();
        jBtn_editar = new javax.swing.JButton();
        jBtn_novo = new javax.swing.JButton();
        jBPro_salvar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTF_cat = new javax.swing.JTextField();
        jBtn_cat_salvar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de produto");
        setMinimumSize(new java.awt.Dimension(800, 680));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPro_tabela.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jPro_tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Categoria", "Estoque", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jPro_tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPro_tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jPro_tabela);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel1.setText("Codigo");

        jPro_codigo.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setText("Estoque");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setText("Preço");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setText("Nome");

        jPro_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPro_nomeActionPerformed(evt);
            }
        });

        jPro_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gin", "Vodka", "Refrigerante", "Sumo", "Comida" }));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel5.setText("Categoria");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel6.setText("Pesquisar");

        jPro_pesquisar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPro_pesquisarFocusGained(evt);
            }
        });
        jPro_pesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPro_pesquisarKeyTyped(evt);
            }
        });

        jBPro_pesquisar.setBackground(new java.awt.Color(255, 255, 255));
        jBPro_pesquisar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jBPro_pesquisar.setText("Pesquisar");
        jBPro_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPro_pesquisarActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/excluir.png"))); // NOI18N
        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jBtn_excluir.setBackground(new java.awt.Color(255, 255, 255));
        jBtn_excluir.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jBtn_excluir.setText("Relatorio");
        jBtn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_excluirActionPerformed(evt);
            }
        });

        jBtn_editar.setBackground(new java.awt.Color(255, 255, 255));
        jBtn_editar.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jBtn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/editar_1_1.png"))); // NOI18N
        jBtn_editar.setText("Editar");
        jBtn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_editarActionPerformed(evt);
            }
        });

        jBtn_novo.setBackground(new java.awt.Color(255, 255, 255));
        jBtn_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/novo.png"))); // NOI18N
        jBtn_novo.setText("Novo");
        jBtn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_novoActionPerformed(evt);
            }
        });

        jBPro_salvar.setBackground(new java.awt.Color(255, 255, 255));
        jBPro_salvar.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jBPro_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/salvar.png"))); // NOI18N
        jBPro_salvar.setText("Salvar");
        jBPro_salvar.setEnabled(false);
        jBPro_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPro_salvarActionPerformed(evt);
            }
        });

        jLabel7.setText("MT");

        jTF_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_catActionPerformed(evt);
            }
        });

        jBtn_cat_salvar.setBackground(new java.awt.Color(255, 255, 255));
        jBtn_cat_salvar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jBtn_cat_salvar.setText("Guardar");
        jBtn_cat_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_cat_salvarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel8.setText("Nova Categoria");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPro_quantidade)
                            .addComponent(jPro_preco, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addComponent(jPro_codigo))
                        .addGap(4, 4, 4)
                        .addComponent(jLabel7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPro_nome)
                                    .addComponent(jPro_categoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPro_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBPro_pesquisar)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_novo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBPro_salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTF_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtn_cat_salvar))
                            .addComponent(jLabel8))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jPro_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jPro_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPro_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPro_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jPro_preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jPro_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBPro_pesquisar))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn_cat_salvar)
                            .addComponent(jTF_cat, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton2)
                                .addComponent(jBtn_editar))
                            .addComponent(jBtn_excluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtn_novo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBPro_salvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPro_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPro_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPro_nomeActionPerformed

    public void limparCampos() {
        jPro_codigo.setText("");
        jPro_nome.setText("");
        jPro_quantidade.setText("");
        jPro_preco.setText("");

    }

    private void jBPro_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPro_salvarActionPerformed
        // Salvar Produto
        Produto obj = new Produto();

        // Verifica se os campos estao vazios
        if (jPro_codigo.getText().equals("")
                && jPro_nome.getText().equals("")
                && jPro_quantidade.getText().equals("")
                && jPro_preco.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Preencha os campos corretamente!");
        } else {
            // Pega os valores inseridos nos campos e armazena na classe Produto
            obj.setPro_nome(jPro_nome.getText().trim());
            obj.setPro_categoria(jPro_categoria.getSelectedItem().toString().trim());
            obj.setPro_quantidade(Integer.parseInt(jPro_quantidade.getText().trim()));
            obj.setPro_preco(Double.parseDouble(jPro_preco.getText().trim()));

            // instancia o DAO e faz executa o metodo de cadastro dos produtos
            ProdutoDAO dao = new ProdutoDAO();
            dao.cadastrarProdutos(obj);

            // Metodo que limpa os campos
            limparCampos();
            listar();
        }
    }//GEN-LAST:event_jBPro_salvarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        // Proessa a lista ao chamar formulario
        listar();
        listarCategorias();
    }//GEN-LAST:event_formWindowActivated

    private void jBtn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_excluirActionPerformed
        // TODO add your handling code here:
        
        ProdutoDAO dao = new ProdutoDAO();
        
        dao.imprimirProdutos();
        
        /*
        * @param METODO QUE APAGA PRODUTO NO BANCO DE DADOS
        */
//        Produto obj = new Produto();
//        int linha = jPro_tabela.getSelectedRow();
//        if (linha == -1) {
//            JOptionPane.showMessageDialog(null, "Selecione a linha que pretende Apagar!");
//        } else {
//
//            int codigoProduto = (int) jPro_tabela.getValueAt(linha, 0);
//
//            obj.setId_produto(codigoProduto);
//            ProdutoDAO dao = new ProdutoDAO();
//            dao.excluirProduto(obj);
//            listar();
//        }
    }//GEN-LAST:event_jBtn_excluirActionPerformed

    private void jBtn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_editarActionPerformed
        // Edita edados do produto:
        Produto obj = new Produto();

        // Verifica se os campos estao vazios
        if (jPro_codigo.getText().equals("")
                && jPro_nome.getText().equals("")
                && jPro_quantidade.getText().equals("")
                && jPro_preco.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Preencha os campos corretamente!");
        } else {
            // Pega os valores inseridos nos campos e armazena na classe Produto
            int codigo = Integer.parseInt(jPro_codigo.getText().trim());
            obj.setPro_nome(jPro_nome.getText().trim());
            obj.setPro_categoria(jPro_categoria.getSelectedItem().toString().trim());
            obj.setPro_quantidade(Integer.parseInt(jPro_quantidade.getText().trim()));
            obj.setPro_preco(Double.parseDouble(jPro_preco.getText().trim()));

            // instancia o DAO e faz executa o metodo de cadastro dos produtos
            ProdutoDAO dao = new ProdutoDAO();
            dao.alterarProduto(obj, codigo);

            // Metodo que limpa os campos
            limparCampos();
        }
        listar();

    }//GEN-LAST:event_jBtn_editarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBtn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_novoActionPerformed
        // TODO add your handling code here:
        limparCampos();
        jBPro_salvar.setEnabled(true);
        jPro_nome.getCursor();
        jBtn_editar.setEnabled(false);
    }//GEN-LAST:event_jBtn_novoActionPerformed

    private void jPro_tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPro_tabelaMouseClicked
        // TODO add your handling code here:
        jBtn_editar.setEnabled(true);
        jBPro_salvar.setEnabled(false);
        int linha = jPro_tabela.getSelectedRow();

        // Pega valores da tabela na linha selcionada
        int codigoProduto = (int) jPro_tabela.getValueAt(linha, 0);
        String nomeProduto = (String) jPro_tabela.getValueAt(linha, 1);
        String categoProduto = (String) jPro_tabela.getValueAt(linha, 2);
        int quantidadeProduto = (int) jPro_tabela.getValueAt(linha, 3);
        double precoProduto = (double) jPro_tabela.getValueAt(linha, 4);

        //diciona os valores nos campos
        jPro_codigo.setText(Integer.toString(codigoProduto));
        jPro_nome.setText(nomeProduto);
        jPro_categoria.setSelectedItem(categoProduto);
        jPro_quantidade.setText(Integer.toString(quantidadeProduto));
        jPro_preco.setText(Double.toString(precoProduto));

    }//GEN-LAST:event_jPro_tabelaMouseClicked

    private void jBPro_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPro_pesquisarActionPerformed
        // TODO add your handling code here:
        String nome = jPro_pesquisar.getText().trim() + "%";
        ProdutoDAO dao = new ProdutoDAO();
        List<Produto> lista = dao.pesquisarProNome(nome);
        DefaultTableModel dados = (DefaultTableModel) jPro_tabela.getModel();
        dados.setNumRows(0);

        for (Produto p : lista) {
            dados.addRow(new Object[]{
                p.getId_produto(),
                p.getPro_nome(),
                p.getPro_categoria(),
                p.getPro_quantidade(),
                p.getPro_preco()
            });
        }

    }//GEN-LAST:event_jBPro_pesquisarActionPerformed

    private void jPro_pesquisarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPro_pesquisarKeyTyped
        // TODO add your handling code here:
        String nome = jPro_pesquisar.getText().trim() + "%";
        ProdutoDAO dao = new ProdutoDAO();
        List<Produto> lista = dao.pesquisarProNome(nome);
        DefaultTableModel dados = (DefaultTableModel) jPro_tabela.getModel();
        dados.setNumRows(0);

        for (Produto p : lista) {
            dados.addRow(new Object[]{
                p.getId_produto(),
                p.getPro_nome(),
                p.getPro_categoria(),
                p.getPro_quantidade(),
                p.getPro_preco()
            });
        }
    }//GEN-LAST:event_jPro_pesquisarKeyTyped

    private void jTF_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_catActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_catActionPerformed

    private void jBtn_cat_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_cat_salvarActionPerformed
        // TODO add your handling code here:

        if (jTF_cat.getText() != null) {
            Categoria obj = new Categoria();
            obj.setNome(jTF_cat.getText().trim());
            CategoriaDAO dao = new CategoriaDAO();
            dao.cadastrarCategoria(obj);
            listarCategorias();
        }else{
            JOptionPane.showMessageDialog(this, "Preencha o Campo corretamente");
        }
        jTF_cat.setText("");
    }//GEN-LAST:event_jBtn_cat_salvarActionPerformed

    private void jPro_pesquisarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPro_pesquisarFocusGained
        // TODO add your handling code here:
        jPro_pesquisar.setText("");
    }//GEN-LAST:event_jPro_pesquisarFocusGained

    // Metodo rque lista os produtos
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBPro_pesquisar;
    private javax.swing.JButton jBPro_salvar;
    private javax.swing.JButton jBtn_cat_salvar;
    private javax.swing.JButton jBtn_editar;
    private javax.swing.JButton jBtn_excluir;
    private javax.swing.JButton jBtn_novo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> jPro_categoria;
    private javax.swing.JTextField jPro_codigo;
    private javax.swing.JTextField jPro_nome;
    private javax.swing.JTextField jPro_pesquisar;
    private javax.swing.JTextField jPro_preco;
    private javax.swing.JTextField jPro_quantidade;
    private javax.swing.JTable jPro_tabela;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTF_cat;
    // End of variables declaration//GEN-END:variables
}
