/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.ItensVendaDAO;
import DAO.MesaDAO;
import DAO.ProdutoDAO;
import DAO.VendaDAO;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ItensVenda;
import model.Mesa;
import model.Produto;
import model.Vendas;

/**
 *
 * @author Klayton Massango
 */
public final class ViewContas extends javax.swing.JFrame {

    /**
     * Creates new form ViewContas
     */
    public String admin, nomeLogado;
    double preco, subtotal, total;
    int qtd;
    DefaultTableModel carrinho;

    public void listarContas() {
        Date data = new Date();
        SimpleDateFormat databr = new SimpleDateFormat("yyyy-MM-dd");
        String dataf = databr.format(data);

        double tota = 0;
        ItensVendaDAO dao = new ItensVendaDAO();
        List<ItensVenda> lista = dao.listaItensVenda(Integer.valueOf(jTF_ms_codigo.getText()), dataf);

        DefaultTableModel dados = (DefaultTableModel) jTable_contas.getModel();

        for (ItensVenda i : lista) {
            jTF_total.setText("");
            tota += i.getSubtotal();
            jTF_total.setText(String.valueOf(tota));
            dados.addRow(new Object[]{
                i.getId(),
                i.getMesas().getMsa_nome(),
                i.getProduto().getPro_nome(),
                i.getQuantidade(),
                i.getPreco(),
                i.getSubtotal()
            });
        }
    }

    public void listarVendas() {
        Date data = new Date();
        SimpleDateFormat databr = new SimpleDateFormat("yyyy-MM-dd");
        String dataf = databr.format(data);

        double tot = 0;
        ItensVendaDAO dao = new ItensVendaDAO();
        List<ItensVenda> lista = dao.listaVenda(dataf);

        DefaultTableModel dados = (DefaultTableModel) jTable_vendas.getModel();
        dados.setNumRows(0);
        for (ItensVenda i : lista) {
            jTF_total_hoje.setText("");
            tot += i.getSubtotal();
            if (!admin.equals("Usuario")) {
                jTF_total_hoje.setText(String.valueOf(tot + " MT"));
            }
            dados.addRow(new Object[]{
                i.getId(),
                i.getMesas().getMsa_nome(),
                i.getData(),
                i.getSubtotal()
            });
        }
    }

    public void listar() {
        ProdutoDAO dao = new ProdutoDAO();
        List<Produto> lista = dao.listarProdutos();
        DefaultTableModel dados = (DefaultTableModel) jTable_con_produtos.getModel();
        dados.setNumRows(0);

        for (Produto p : lista) {
            dados.addRow(new Object[]{
                p.getId_produto(),
                p.getPro_nome(),
                p.getPro_categoria(),
                p.getPro_quantidade(),
                p.getPro_preco(),});
        }
    }

    public ViewContas() {
        initComponents();
        setIconImage();
        setResizable(false);
        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTP_menu = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jBtn_psr_prodoto = new javax.swing.JButton();
        jTF_psr_produto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTF_total = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBtn_novacon = new javax.swing.JButton();
        jBtn_adicionarcon = new javax.swing.JButton();
        jBtn_imprimir_con = new javax.swing.JButton();
        jBtn_remover_con = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_contas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_con_produtos = new javax.swing.JTable();
        jTF_codigo_pro = new javax.swing.JTextField();
        jTF_produto_pro = new javax.swing.JTextField();
        jTF_estoque_pro = new javax.swing.JTextField();
        jTF_preco_pro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComb_mesa = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jTF_quantidade_req = new javax.swing.JFormattedTextField();
        jTf_data = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTF_ms_codigo = new javax.swing.JTextField();
        jBtn_void = new javax.swing.JButton();
        Lbl_func_nome = new javax.swing.JLabel();
        jBtn_Habilitar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_vendas = new javax.swing.JTable();
        jBtn_Fechar_conta = new javax.swing.JButton();
        jTF_total_hoje = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CONTAS E PAGAMENTOS");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTP_menu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTP_menuFocusGained(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setText("Pesquisar Produto");

        jBtn_psr_prodoto.setBackground(new java.awt.Color(255, 255, 255));
        jBtn_psr_prodoto.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jBtn_psr_prodoto.setText("Pesquisar");
        jBtn_psr_prodoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_psr_prodotoActionPerformed(evt);
            }
        });

        jTF_psr_produto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTF_psr_produtoKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("VALOR TOTAL");

        jTF_total.setEditable(false);
        jTF_total.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel2.setText("MT");

        jBtn_novacon.setBackground(new java.awt.Color(255, 255, 255));
        jBtn_novacon.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtn_novacon.setText("Fechar");
        jBtn_novacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_novaconActionPerformed(evt);
            }
        });

        jBtn_adicionarcon.setBackground(new java.awt.Color(255, 255, 255));
        jBtn_adicionarcon.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtn_adicionarcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/add1.png"))); // NOI18N
        jBtn_adicionarcon.setText("Adicionar");
        jBtn_adicionarcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_adicionarconActionPerformed(evt);
            }
        });

        jBtn_imprimir_con.setBackground(new java.awt.Color(255, 255, 255));
        jBtn_imprimir_con.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtn_imprimir_con.setText("Imprimir");
        jBtn_imprimir_con.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_imprimir_conActionPerformed(evt);
            }
        });

        jBtn_remover_con.setBackground(new java.awt.Color(255, 255, 255));
        jBtn_remover_con.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtn_remover_con.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/excluir.png"))); // NOI18N
        jBtn_remover_con.setText("Remover");
        jBtn_remover_con.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_remover_conActionPerformed(evt);
            }
        });

        jTable_contas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable_contas.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jTable_contas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NrConta", "Mesa", "Produto", "QTD", "Preco", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_contas);
        if (jTable_contas.getColumnModel().getColumnCount() > 0) {
            jTable_contas.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable_contas.getColumnModel().getColumn(1).setPreferredWidth(30);
            jTable_contas.getColumnModel().getColumn(4).setPreferredWidth(20);
        }

        jTable_con_produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nr", "Nome", "Categoria", "QTD", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_con_produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_con_produtosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_con_produtos);
        if (jTable_con_produtos.getColumnModel().getColumnCount() > 0) {
            jTable_con_produtos.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTable_con_produtos.getColumnModel().getColumn(2).setPreferredWidth(15);
            jTable_con_produtos.getColumnModel().getColumn(3).setPreferredWidth(20);
            jTable_con_produtos.getColumnModel().getColumn(4).setPreferredWidth(15);
        }

        jTF_codigo_pro.setEditable(false);

        jTF_produto_pro.setEditable(false);

        jTF_estoque_pro.setEditable(false);

        jTF_preco_pro.setEditable(false);

        jLabel4.setText("Código");

        jLabel5.setText("Produto");

        jLabel6.setText("Estoque");

        jLabel7.setText("Preço");

        jLabel8.setText("QTD Req.");

        jComb_mesa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComb_mesaItemStateChanged(evt);
            }
        });
        jComb_mesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComb_mesaActionPerformed(evt);
            }
        });

        jLabel9.setText("Mesa");

        jTF_quantidade_req.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jTf_data.setEditable(false);

        jLabel10.setText("Data");

        jTF_ms_codigo.setEditable(false);

        jBtn_void.setBackground(new java.awt.Color(255, 255, 255));
        jBtn_void.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtn_void.setText("Void");
        jBtn_void.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_voidActionPerformed(evt);
            }
        });

        Lbl_func_nome.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        Lbl_func_nome.setText("Nome do Funcionario");

        jBtn_Habilitar.setBackground(new java.awt.Color(255, 255, 255));
        jBtn_Habilitar.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jBtn_Habilitar.setText("Nova");
        jBtn_Habilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_HabilitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtn_imprimir_con, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jBtn_remover_con, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtn_adicionarcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBtn_novacon, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn_void, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Lbl_func_nome))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtn_Habilitar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_psr_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtn_psr_prodoto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTF_ms_codigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(29, 29, 29))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jComb_mesa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTF_codigo_pro, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jTF_produto_pro, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jTF_estoque_pro, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(33, 33, 33))
                                            .addComponent(jTF_preco_pro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jTF_quantidade_req, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTf_data, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTF_total, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTF_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jTf_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTF_estoque_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTF_quantidade_req)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF_preco_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(7, 7, 7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComb_mesa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTF_ms_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBtn_novacon, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTF_produto_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(41, 41, 41)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTF_codigo_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(41, 41, 41))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn_adicionarcon, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_psr_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn_psr_prodoto)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBtn_remover_con, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtn_imprimir_con, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtn_void, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtn_Habilitar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Lbl_func_nome)))))
                .addContainerGap())
        );

        jTP_menu.addTab("Mesas", jPanel1);

        jTable_vendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Conta", "Mesa", "Data", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable_vendas);

        jBtn_Fechar_conta.setBackground(new java.awt.Color(255, 255, 255));
        jBtn_Fechar_conta.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jBtn_Fechar_conta.setText("FECHAR");
        jBtn_Fechar_conta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_Fechar_contaActionPerformed(evt);
            }
        });

        jTF_total_hoje.setEditable(false);
        jTF_total_hoje.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jTF_total_hoje.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel11.setText("TOTAL DIARIO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1039, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtn_Fechar_conta, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTF_total_hoje, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtn_Fechar_conta, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTF_total_hoje, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE))
        );

        jTP_menu.addTab("Contas", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTP_menu)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTP_menu)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        MesaDAO dao = new MesaDAO();
        List<Mesa> lista = dao.listarMesas();

        jComb_mesa.removeAllItems();
        for (Mesa mesa : lista) {
            jComb_mesa.addItem(mesa);
        }
        // Coverte a data padrao para a data nacional
        Date data = new Date();
        SimpleDateFormat databr = new SimpleDateFormat("dd/MM/yyyy");
        String dataf = databr.format(data);

        jTf_data.setText(String.valueOf(dataf));

        listar();
        listarVendas();
        if (admin.equals("Usuario")) {
            jBtn_remover_con.setVisible(false);
        }
    }//GEN-LAST:event_formWindowActivated

    private void jBtn_adicionarconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_adicionarconActionPerformed
        String nome = jTF_produto_pro.getText();

        Date data = new Date();
        SimpleDateFormat dataSql = new SimpleDateFormat("yyyy-MM-dd");
        String dat = dataSql.format(data);
        if (jTF_codigo_pro.getText().equals("")
                && jTF_estoque_pro.getText().equals("")
                && jTF_preco_pro.getText().equals("")
                && jTF_produto_pro.getText().equals("")
                && jTF_quantidade_req.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Preencha os campos corretamente!");
        } else {
            if (nome != null && jTF_quantidade_req.getText() != null) {
                int quantidade = Integer.valueOf(jTF_quantidade_req.getText().trim());
                int estoque = Integer.valueOf(jTF_estoque_pro.getText().trim());
                preco = Double.valueOf(jTF_preco_pro.getText().trim());
                qtd = Integer.valueOf(jTF_quantidade_req.getText().trim());
                subtotal = preco * qtd;
                int baixaestoque = estoque - quantidade;

                if (quantidade <= estoque && jTF_quantidade_req.getText() != null) {
                    ItensVenda iv = new ItensVenda();
                    Produto p = new Produto();
                    Mesa m = new Mesa();

                    p.setId_produto(Integer.valueOf(jTF_codigo_pro.getText().trim()));
                    m.setMsa_id(Integer.valueOf(jTF_ms_codigo.getText().trim()));
                    iv.setProduto(p);
                    iv.setMesas(m);
                    iv.setQuantidade(Integer.valueOf(jTF_quantidade_req.getText().trim()));
                    iv.setPreco(Double.valueOf(jTF_preco_pro.getText().trim()));
                    iv.setSubtotal(subtotal);
                    iv.setData(dat);
                    p.setPro_quantidade(baixaestoque);

                    ItensVendaDAO ivdao = new ItensVendaDAO();
                    ProdutoDAO dao = new ProdutoDAO();

                    ivdao.cadastrarItensVenda(iv);

                    dao.baixaEstoque(p, Integer.valueOf(jTF_codigo_pro.getText().trim()));
                    DefaultTableModel dados = (DefaultTableModel) jTable_contas.getModel();
                    dados.setNumRows(0);
                    listar();
                    jTF_estoque_pro.setText("");
                    jTF_produto_pro.setText("");
                    jTF_codigo_pro.setText("");
                    jTF_produto_pro.setText("");
                    jTF_preco_pro.setText("");

                    MesaDAO daoo = new MesaDAO();
                    List<Mesa> lista = daoo.listarMesas();
                    jTF_quantidade_req.setText("");
                    listarContas();

                } else {
                    JOptionPane.showMessageDialog(this, "Quantidade de Estoque indisponível");
                }

            } else {
                JOptionPane.showMessageDialog(this, "Selecione o produto!");
            }
        }
    }//GEN-LAST:event_jBtn_adicionarconActionPerformed

    private void jTable_con_produtosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_con_produtosMouseClicked
        // TODO add your handling code here:
        int linha = jTable_con_produtos.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(null, "Selecione a linha que pretende Editar!");
        } else {

            // Pega valores da tabela na linha selcionada
            int codigoProduto = (int) jTable_con_produtos.getValueAt(linha, 0);
            String nomeProduto = (String) jTable_con_produtos.getValueAt(linha, 1);
            String categoProduto = (String) jTable_con_produtos.getValueAt(linha, 2);
            int quantidadeProduto = (int) jTable_con_produtos.getValueAt(linha, 3);
            double precoProduto = (double) jTable_con_produtos.getValueAt(linha, 4);

            //diciona os valores nos campos
            jTF_codigo_pro.setText(Integer.toString(codigoProduto));
            jTF_produto_pro.setText(nomeProduto);
            jTF_estoque_pro.setText(Integer.toString(quantidadeProduto));
            jTF_preco_pro.setText(Double.toString(precoProduto));

        }

    }//GEN-LAST:event_jTable_con_produtosMouseClicked

    private void jBtn_psr_prodotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_psr_prodotoActionPerformed
        // TODO add your handling code here:
        String nome = jTF_psr_produto.getText() + "%";
        if (nome != null) {
            ProdutoDAO dao = new ProdutoDAO();
            List<Produto> lista = dao.pesquisarProNome(nome);
            DefaultTableModel dados = (DefaultTableModel) jTable_con_produtos.getModel();
            dados.setNumRows(0);

            for (Produto p : lista) {
                dados.addRow(new Object[]{
                    p.getId_produto(),
                    p.getPro_nome(),
                    p.getPro_categoria(),
                    p.getPro_quantidade(),
                    p.getPro_preco()
                });
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pesquisa Invalida!");
        }
    }//GEN-LAST:event_jBtn_psr_prodotoActionPerformed

    private void jTF_psr_produtoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_psr_produtoKeyTyped
        // TODO add your handling code here:

        String nome = jTF_psr_produto.getText() + "%";
        ProdutoDAO dao = new ProdutoDAO();
        List<Produto> lista = dao.pesquisarProNome(nome);
        DefaultTableModel dados = (DefaultTableModel) jTable_con_produtos.getModel();
        dados.setNumRows(0);

        for (Produto p : lista) {
            dados.addRow(new Object[]{
                p.getId_produto(),
                p.getPro_nome(),
                p.getPro_categoria(),
                p.getPro_quantidade(),
                p.getPro_preco()
            });
        }
    }//GEN-LAST:event_jTF_psr_produtoKeyTyped

    private void jComb_mesaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComb_mesaItemStateChanged
        // TODO add your handling code here:
        try {
            String nome = jComb_mesa.getSelectedItem().toString();
            MesaDAO dao = new MesaDAO();
            Mesa obj = new Mesa();
            obj.setMsa_nome(nome);
            dao.pegarIdMesa(obj);

            jTF_ms_codigo.setText(String.valueOf(obj.getMsa_id()));
            jTF_total.setText("");

            DefaultTableModel dados = (DefaultTableModel) jTable_contas.getModel();
            dados.setNumRows(0);
            listarContas();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jComb_mesaItemStateChanged

    private void jBtn_imprimir_conActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_imprimir_conActionPerformed
        // TODO add your handling code here:
        jBtn_imprimir_con.setEnabled(false);
        Date data = new Date();
        SimpleDateFormat dataSql = new SimpleDateFormat("yyyy-MM-dd");
        String dat = dataSql.format(data);

        ItensVendaDAO dao = new ItensVendaDAO();
        int mesa = Integer.valueOf(jTF_ms_codigo.getText());
        dao.imprimirConta(mesa, dat);


    }//GEN-LAST:event_jBtn_imprimir_conActionPerformed

    private void jBtn_remover_conActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_remover_conActionPerformed
        // TODO add your handling code here:
        try {
            ItensVenda obj = new ItensVenda();
            ItensVendaDAO dao = new ItensVendaDAO();
            Produto p = new Produto();
            ProdutoDAO pdao = new ProdutoDAO();

            int linha = jTable_contas.getSelectedRow();
            int codigo = (int) jTable_contas.getValueAt(linha, 0);
            String nome = (String) jTable_contas.getValueAt(linha, 2);
            int qtd = (int) jTable_contas.getValueAt(linha, 3);

            pdao.nomeProdutoQtd(nome, qtd);
            obj.setId(codigo);
            dao.excluirItenVenda(obj);

            DefaultTableModel dados = (DefaultTableModel) jTable_contas.getModel();
            dados.setNumRows(0);
            listarContas();
            jTF_total.setText("");
            jTF_estoque_pro.setText("");
            listar();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jBtn_remover_conActionPerformed

    private void jBtn_Fechar_contaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_Fechar_contaActionPerformed
        // TODO add your handling code here:

        /**
         * ELABORAR UM SCRIPT QUE GUARDE TODAS CONTAS DA DATA ATUAL NA TABELA DE
         * VENDAS INSERINDO OS VALORES DE
         *
         * @param id_conta
         * @param total
         * @param data E AO GUARDAR ALTERE O VALOR DE INATIVO PARA 2 DA TABELA
         * DE CONTAS
         */
        int linha = jTable_vendas.getRowCount();
        jTable_vendas.selectAll();
        int lin = jTable_vendas.getSelectedRow();

        while (linha != 0) {
            Vendas obj = new Vendas();
            VendaDAO dao = new VendaDAO();
            ItensVendaDAO vdao = new ItensVendaDAO();
            System.out.println(linha);
            // Pega valores da tabela na linha selcionada
            int codigo = (int) jTable_vendas.getValueAt(lin, 0);
            String data = (String) jTable_vendas.getValueAt(lin, 2);
            double subtotal = (double) jTable_vendas.getValueAt(lin, 3);
            obj.setId(codigo);
            obj.setVd_data(data);
            obj.setVd_total(subtotal);

            dao.cadastrarVenda(obj);
            vdao.finalizarVendas(codigo);
            linha -= linha;
        }
        System.out.println("fim");
        listarVendas();

    }//GEN-LAST:event_jBtn_Fechar_contaActionPerformed

    private void jTP_menuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTP_menuFocusGained
        // TODO add your handling code here:
        DefaultTableModel dados = (DefaultTableModel) jTable_vendas.getModel();
        dados.setNumRows(0);
        listarVendas();
    }//GEN-LAST:event_jTP_menuFocusGained

    private void jBtn_novaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_novaconActionPerformed
        // TODO add your handling code here:
        Date data = new Date();
        SimpleDateFormat dataSql = new SimpleDateFormat("yyyy-MM-dd");
        String dat = dataSql.format(data);

        ItensVendaDAO dao = new ItensVendaDAO();
        int mesa = Integer.valueOf(jTF_ms_codigo.getText());
        dao.imprimirConta(mesa, dat);
        dao.finalizarConta(mesa, dat);
    }//GEN-LAST:event_jBtn_novaconActionPerformed

    private void jBtn_voidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_voidActionPerformed
        // TODO add your handling code here:

        /**
         * Fazer void de produtos Para fazer void do produto é necessario pegar
         * o id da produto na tabela de contas e alterar o id da mesa na conta
         * especifica
         *
         * @param jTable_contas,
         */
        ItensVendaDAO dao = new ItensVendaDAO();

        int linha = jTable_contas.getSelectedRow();
        int codigo = (int) jTable_contas.getValueAt(linha, 0);

        dao.voidProduto(codigo);
        listarVendas();

    }//GEN-LAST:event_jBtn_voidActionPerformed

    private void jComb_mesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComb_mesaActionPerformed
        // TODO add your handling code here:
        if (jComb_mesa.getSelectedIndex() == 0) {
            jTF_ms_codigo.setText(String.valueOf(1));
        }
    }//GEN-LAST:event_jComb_mesaActionPerformed

    private void jBtn_HabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_HabilitarActionPerformed
        // TODO add your handling code here:
        jBtn_imprimir_con.setEnabled(true);
    }//GEN-LAST:event_jBtn_HabilitarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewContas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_func_nome;
    private javax.swing.JButton jBtn_Fechar_conta;
    private javax.swing.JButton jBtn_Habilitar;
    private javax.swing.JButton jBtn_adicionarcon;
    private javax.swing.JButton jBtn_imprimir_con;
    private javax.swing.JButton jBtn_novacon;
    private javax.swing.JButton jBtn_psr_prodoto;
    private javax.swing.JButton jBtn_remover_con;
    private javax.swing.JButton jBtn_void;
    private javax.swing.JComboBox jComb_mesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTF_codigo_pro;
    private javax.swing.JTextField jTF_estoque_pro;
    private javax.swing.JTextField jTF_ms_codigo;
    private javax.swing.JTextField jTF_preco_pro;
    private javax.swing.JTextField jTF_produto_pro;
    private javax.swing.JTextField jTF_psr_produto;
    private javax.swing.JFormattedTextField jTF_quantidade_req;
    private javax.swing.JTextField jTF_total;
    private javax.swing.JTextField jTF_total_hoje;
    private javax.swing.JTabbedPane jTP_menu;
    private javax.swing.JTable jTable_con_produtos;
    private javax.swing.JTable jTable_contas;
    private javax.swing.JTable jTable_vendas;
    private javax.swing.JTextField jTf_data;
    // End of variables declaration//GEN-END:variables
public void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
}
