/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Klayton Massango
 */
public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewPrincipal
     */
    public String admin, nomeLogado;

    public ViewPrincipal() {
        initComponents();

        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setIconImage();
    }
    public void setIconImage(){
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
}
//    public void verificaNivelacesso()

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        uJPanelImagem9 = new componentes.UJPanelImagem();
        jBtn_contas = new javax.swing.JButton();
        jBtn_produtos = new javax.swing.JButton();
        jBtn_relatorios = new javax.swing.JButton();
        jBtn_sair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLbl_nome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        uJPanelImagem1 = new componentes.UJPanelImagem();
        jMenuBar1 = new javax.swing.JMenuBar();

        jButton3.setText("jButton3");

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 680));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jBtn_contas.setBackground(new java.awt.Color(255, 255, 255));
        jBtn_contas.setFont(new java.awt.Font("Vodafone ExB", 0, 18)); // NOI18N
        jBtn_contas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/editar_1_1.png"))); // NOI18N
        jBtn_contas.setText("Contas");
        jBtn_contas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_contasActionPerformed(evt);
            }
        });

        jBtn_produtos.setBackground(new java.awt.Color(255, 255, 255));
        jBtn_produtos.setFont(new java.awt.Font("Vodafone ExB", 0, 18)); // NOI18N
        jBtn_produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/buscar.png"))); // NOI18N
        jBtn_produtos.setText("Produtos");
        jBtn_produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_produtosActionPerformed(evt);
            }
        });

        jBtn_relatorios.setBackground(new java.awt.Color(255, 255, 255));
        jBtn_relatorios.setFont(new java.awt.Font("Vodafone ExB", 0, 18)); // NOI18N
        jBtn_relatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/Login_48x48.png"))); // NOI18N
        jBtn_relatorios.setText("Admin");
        jBtn_relatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_relatoriosActionPerformed(evt);
            }
        });

        jBtn_sair.setBackground(new java.awt.Color(255, 255, 255));
        jBtn_sair.setFont(new java.awt.Font("Vodafone ExB", 0, 18)); // NOI18N
        jBtn_sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons/excluir.png"))); // NOI18N
        jBtn_sair.setText("Sair");
        jBtn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_sairActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Sistema de Gestão");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel5.setText("Nome:");

        jLbl_nome.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLbl_nome.setText("Hipolito Sancho");
        jLbl_nome.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addGap(456, 456, 456)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLbl_nome)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(jLbl_nome))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 10)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("2021 Maze Dev. Todos Direitos reservados Termos e Condicoes aplicaveis.");

        uJPanelImagem1.setImagem(new java.io.File("C:\\gestorimgs\\brand3.png"));

        javax.swing.GroupLayout uJPanelImagem1Layout = new javax.swing.GroupLayout(uJPanelImagem1);
        uJPanelImagem1.setLayout(uJPanelImagem1Layout);
        uJPanelImagem1Layout.setHorizontalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        uJPanelImagem1Layout.setVerticalGroup(
            uJPanelImagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout uJPanelImagem9Layout = new javax.swing.GroupLayout(uJPanelImagem9);
        uJPanelImagem9.setLayout(uJPanelImagem9Layout);
        uJPanelImagem9Layout.setHorizontalGroup(
            uJPanelImagem9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(uJPanelImagem9Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jBtn_contas)
                .addGap(40, 40, 40)
                .addComponent(jBtn_produtos)
                .addGap(33, 33, 33)
                .addComponent(jBtn_relatorios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtn_sair)
                .addGap(35, 35, 35))
            .addGroup(uJPanelImagem9Layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(287, 287, 287))
        );
        uJPanelImagem9Layout.setVerticalGroup(
            uJPanelImagem9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uJPanelImagem9Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(uJPanelImagem9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_contas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_produtos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_relatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(uJPanelImagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJPanelImagem9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_produtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_produtosActionPerformed
        // TODO add your handling code here:
        new ViewProdutos().setVisible(true);
    }//GEN-LAST:event_jBtn_produtosActionPerformed

    private void jBtn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_sairActionPerformed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(null, "Tem certeza que pretende sair?");
        if (op == 0) {
            System.exit(0);
        } else if (op == 2) {
            JOptionPane.showMessageDialog(null, "Operação Cancelada");
        }
    }//GEN-LAST:event_jBtn_sairActionPerformed

    private void jBtn_contasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_contasActionPerformed
        // TODO add your handling code here:

        ViewContas contas = new ViewContas();
        contas.admin = admin;
        contas.setVisible(true);
    }//GEN-LAST:event_jBtn_contasActionPerformed

    private void jBtn_relatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_relatoriosActionPerformed
        // TODO add your handling code here:
        new ViewAdministrador().setVisible(true);
    }//GEN-LAST:event_jBtn_relatoriosActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        jLbl_nome.setText(nomeLogado);
        if (admin.equals("Administrador")) {
            jBtn_relatorios.setVisible(true);
        } else if (admin.equals("Usuario")) {
            jBtn_relatorios.setVisible(false);
            jBtn_produtos.setVisible(false);
        }
        if (admin.equals("Master")) {
            jBtn_relatorios.setVisible(false);
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_contas;
    private javax.swing.JButton jBtn_produtos;
    private javax.swing.JButton jBtn_relatorios;
    private javax.swing.JButton jBtn_sair;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLbl_nome;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private componentes.UJPanelImagem uJPanelImagem1;
    private componentes.UJPanelImagem uJPanelImagem9;
    // End of variables declaration//GEN-END:variables
}
